org: thattallman10
app: face-auth-serverless
service: face-auth-serverless
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x
functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
